update packages
squalus/flake pull request #1
Opened 2023-10-28 17:22 UTC by icewind1991

Update the packages and adjust to the now-required java21

2023-10-29 08:16 UTC, squalus requested changes
Thanks for the PR. This mostly matches the unfinished work I have. `piped-test` fails now, though.

```
vm-test-run-piped-integration-test> machine # [  925.063666] postgres[8869]: [8869] ERROR:  permission denied for schema public at character 14
vm-test-run-piped-integration-test> machine # [  925.064087] postgres[8869]: [8869] STATEMENT:  CREATE TABLE public.databasechangelog (ID VARCHAR(255) NOT NULL, AUTHOR VARCHAR(255) NOT NULL, FILENAME VARCHAR(255) NOT NULL, DATEEXECUTED TIMESTAMP WITHOUT TIME ZONE NOT NULL, ORDEREXECUTED INTEGER NOT NULL, EXECTYPE VARCHAR(10) NOT NULL, MD5SUM VARCHAR(35), DESCRIPTION VARCHAR(255), COMMENTS VARCHAR(255), TAG VARCHAR(255), LIQUIBASE VARCHAR(20), CONTEXTS VARCHAR(255), LABELS VARCHAR(255), DEPLOYMENT_ID VARCHAR(10))

```

2023-10-29 08:16 UTC, squalus commented on piped-backend/default.nix
> +{ src, stdenv, fetchFromGitHub, lib, gradle, perl, runtimeShell, jdk, nixosTest, dos2unix }:
Renaming the input to `jdk` is a good change.

2023-10-29 08:16 UTC, squalus commented on piped-backend/default.nix
> +      dos2unix src/main/java/me/kavin/piped/Main.java
The patch should be a diff on the unmodified upstream file. (Unless this is a pre-existing nixpkgs convention that I'm unware of).

2023-11-01 21:23 UTC, icewind1991 commented on piped-backend/default.nix
> +      dos2unix src/main/java/me/kavin/piped/Main.java
The source seems to be in dos line endings, and having the patch be in dos line endings wasn't working for me, `patch` would just print an "ignoring extra \r at end of line" and than fail to apply it.

Converting the line endings of the patched file was the only way I got it to apply.

2023-11-04 14:22 UTC, icewind1991 commented
Fixed the postgresql issue with the tests, `piped-test` still fails for me though since it requires internet access

2023-11-04 19:26 UTC, squalus commented
I no longer see the permissions error in piped-test.

piped-test has to be run with the sandbox turned off because of the internet access issue, like this: `nix build -L .#piped-test --option build-use-sandbox false`.

piped-test still fails for me. When trying it out in the interactive machine, like with `nix build -L .#piped-test.driverInteractive`, it's a blank page in chromium. The network requests to piped-backend hang.

This hangs: `curl -v 'http://127.0.0.1:14302/trending?region=US'`

Did you perform any manual testing on this, and did it work fine for you?

2023-11-04 19:38 UTC, icewind1991 commented
> Did you perform any manual testing on this, and did it work fine for you?

I've been using a [version of this that uses mostly stable nixpkgs](https://github.com/icewind1991/piped-flake/tree/stable23.05) for over a week without issues.

2023-11-10 08:17 UTC, squalus commented
I fixed the piped-test hang by increasing cores from 1 to 3. Piped-Backend was hanging in the DownloaderImpl while NewPipeExtractor was trying to fetch the sw.js file, on the newVirtualThreadPerTaskExecutor. Seems like some bug on the Piped-Backend side.

2023-11-10 08:18 UTC, merged